name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode & Create Keystore Properties(Base64)
      env:
        kEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
      run:
        echo "KEYSTORE_PROPERTIES" | base64 --decode > ./keystore.properties

    - name: Create Local Properties
      env:
        LOCAL_PROPERTIES: ${{secrets.LOCAL_PROPERTIES}}
      run:
        echo "LOCAL_PROPERTIES" > ./local.properties

    - name: Create Google Services JSON
      env:
        GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
      run:
        echo "GOOGLE_SERVICES_JSON" > ./app/google-services.json
    
    - name: Build with Gradle
      run: ./gradlew build --no-deamon

    - name: Run ktlintCheck
      run: ./gradlew ktlintCheck --no-daemon
